# Generated by Django 4.2.10 on 2025-05-11 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investmentfund",
            name="fund_type",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="investmentfund",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="investmentfund",
            name="ticker",
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="fund",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="core.investmentfund",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("aporte", "Aporte"), ("resgate", "Resgate")],
                db_index=True,
                max_length=7,
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["fund", "transaction_type"],
                name="core_transa_fund_id_a2a640_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["date", "fund"], name="core_transa_date_427377_idx"
            ),
        ),
    ]
